version: '2.4'
services:
  registry:
    image: registry:2
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/server.crt
      REGISTRY_HTTP_TLS_KEY: /certs/server.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - $PWD/compose/certs:/certs
      - $PWD/compose/auth:/auth
  docker:
    privileged: true
    image: docker:25-dind
    environment:
      DOCKER_TLS_CERTDIR: ''
      DOCKER_BUILDKIT: 1
    command: [
      "--insecure-registry=registry:5000"
    ]

