version: '2.4'
services:
  semantic-release:
    build:
      context: ../
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_BUILDKIT: 1
      TEST_DOCKER_REGISTRY: registry:5000
    command: npm run tap
    depends_on:
      - docker
      - registry
