name: Test + Release

on:
  pull_request:
    branches:
      - master

  push:
    branch:
      - master
jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install
        uses: actions/setup-node@v1
        with:
          node-version: 24

      - name: test
        run: npm test

  release:
    name: Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install

      - name: Publish
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GIT_AUTHOR_NAME: 'Dependant Bot'
          GIT_AUTHOR_EMAIL: 'release-bot@codedependant.net'
          GIT_COMMITTER_NAME: 'Dependant Bot'
          GIT_COMMITTER_EMAIL: 'release-bot@codedependant.net'
          NPM_TOKEN: 'false'
